# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision "shell", inline: <<-SHELL
sudo apt-get update

# Build dependencies
sudo apt-get install -y apache2 apache2-dev vim git autoconf automake pkg-config libtool wget libxml2-dev libssh2-1-dev gcc g\+\+ zlib1g-dev libssl-dev cmake libpcre3-dev libjson-c-dev make libxslt-dev libcurl4-openssl-dev libtool xsltproc python-setuptools libapr1-dev libaprutil1-dev sysv-rc-conf

# PHP dependencies:
sudo apt-get install -y php5 php5-common php5-json php5-sqlite php5-odbc php5-intl

export PKG_CONFIG_PATH=${PKG_CONFIG_PATH}:/usr/lib64/pkgconfig
alias chkconfig=sysv-rc-conf

# libssh
(
	wget https://red.libssh.org/attachments/download/177/libssh-0.7.2.tar.xz
	tar -xJf libssh-0.7.2.tar.xz
	mkdir -p libssh-0.7.2/build
	cd libssh-0.7.2/build
	cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr .. && make -j2 && sudo make install
)

(
	git clone --depth 1 https://github.com/CESNET/libyang.git
	mkdir -p libyang/build
	cd libyang/build
	cmake -DCMAKE_INSTALL_PREFIX=/usr -DLIB_INSTALL_DIR=lib64 -DENABLE_BUILD_TESTS=OFF .. && sudo make install && sudo make install
)

(
	wget https://cmocka.org/files/1.0/cmocka-1.0.1.tar.xz
	tar -xJf cmocka-1.0.1.tar.xz
	mkdir -p cmocka-1.0.1/build
	cd cmocka-1.0.1/build
	cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr .. && make -j2 && sudo make install
)

(
	git clone --depth 1 https://github.com/warmcat/libwebsockets.git lws
	mkdir lws/b
	cd lws/b
	cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DLWS_INSTALL_LIB_DIR=/usr/lib64 -DLIB_SUFFIX= .. && sudo make install
)

# libnetconf2
(
	git clone --depth 1 https://github.com/CESNET/libnetconf2.git
	mkdir -p libnetconf2/build
	cd libnetconf2/build
	cmake -DENABLE_TLS=ON -DENABLE_SSH=ON -DENABLE_BUILD_TESTS=OFF -DCMAKE_INSTALL_PREFIX=/usr -DLIB_INSTALL_DIR=lib64 .. && sudo make install
)
ldconfig

# netopeerguid
(
	git clone --depth 1 https://github.com/CESNET/netopeerguid
	cd netopeerguid
	./bootstrap.sh
	./configure
	make
	make install
)
   SHELL
end
