imports:
    - { resource: config_dev.yml }

parameters:
    netopeer.data.class: FIT\NetopeerBundle\Tests\_files\MockClass\Data

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
