FITNetopeerBundle:
    resource: "@FITNetopeerBundle/Controller"
    type:     annotation
    prefix:   /

login:
    pattern:   /login
    defaults:  { _controller: NetopeerBundle:Security:login }
login_check:
    pattern:   /login_check


# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
