FITNetopeerBundle:
    resource: "@FITNetopeerBundle/Controller"
    type:     annotation
    prefix:   /

fit_module_default:
    resource: "@FITModuleDefaultBundle/Controller/"
    type:     annotation
    prefix:   /

_login:
    pattern:   /login
    defaults:  { _controller: FITNetopeerBundle:Security:login }

login_check:
    pattern:   /login_check

# saml bundle
aerialship_saml_sp_bundle:
    resource: "@AerialShipSamlSPBundle/Resources/config/routing.yml"


# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
