security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FIT\NetopeerBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers:          [user_db, in_memory]
        user_db:
            entity: { class: FITNetopeerBundle:User, property: username }
        in_memory:
            memory:
                users:
                    user:           { password: pass,    roles: [ 'ROLE_USER' ] }
                    adminNoDb:      { password: pass,    roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^
            anonymous:  ~
            form_login:
                check_path: /login_check
                login_path: /login/
            logout:
                path:   /logout/
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/, roles: ROLE_USER}
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
