security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FIT\NetopeerBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers:          [user_db, in_memory]
        user_db:
            entity: { class: FITNetopeerBundle:User, property: username }
        saml_user_provider:
            id: SamlToState
        in_memory:
            memory:
                users:
                    user:           { password: pass,    roles: [ 'ROLE_USER' ] }
                    adminNoDb:      { password: pass,    roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        saml:
            pattern: ^/
            anonymous: false
            aerial_ship_saml_sp:
                login_path: /saml/sp/login
                check_path: /saml/sp/acs
                logout_path: /saml/sp/logout
                failure_path: /saml/sp/failure
                metadata_path: /saml/sp/FederationMetadata.xml
                discovery_path: /saml/sp/discovery
                local_logout_path: /logout/
                provider: saml_user_provider
                create_user_if_not_exists: true
                services:
                    openidp:
                        idp:
                            file: "@FITNetopeerBundle/Resources/saml/openidp.metadata.xml"
                        sp:
                            config:
                                # required
                                entity_id: netconfwebgui4
                                # if different then url being used in request
                                # used for construction of assertion consumer and logout urls in SP entity descriptor
                                base_url: https://garnacha.liberouter.org/netconfwebgui/app_dev.php
                            signing:
                                # must implement SPSigningProviderInterface
                                # id: my.signing.provider.service.id

                                # or use built in SPSigningProviderFile with specific certificate and key files
                                cert_file: "@FITNetopeerBundle/Resources/saml/server.pem"
                                key_file: "@FITNetopeerBundle/Resources/saml/server.key"
                                key_pass: ""
                            meta:
                                # must implement SpMetaProviderInterface
                                # id: my.sp.provider.service.id

                                # or use builtin SpMetaConfigProvider
                                # any valid saml name id format or shortcuts: persistent or transient
                                name_id_format: transient
                                binding:
                                    # any saml binding or shortcuts: post or redirect
                                    authn_request: post
                                    logout_request: post
            logout:
                path: /logout

        secured_area:
            pattern:    ^
            anonymous:  ~
            form_login:
                check_path: /login_check
                login_path: /login/
            logout:
                path:   /logout/
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/saml/sp/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/saml/sp/acs, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER}
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
