<?php

namespace FIT\NetopeerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ModuleControllerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleControllerRepository extends EntityRepository
{
}
