# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.ssh.insert_key = false

  config.vm.network "forwarded_port", guest: 80, host: 2280

  config.vm.provision "shell" do |s|
        s.path = "centos7/install.sh"
  end
end
