homepage:
    pattern:  /
    defaults: { _controller: NetopeerBundle:Default:index }

_login:
    pattern:   /login
    defaults:  { _controller: NetopeerBundle:Security:login }
_login_check:
    pattern:   /login_check
_logout:
    pattern:  /logout
