# @author David Alexa <alexa.david@me.com>
#
# Copyright (C) 2012-2013 CESNET
#
# LICENSE TERMS
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in
#    the documentation and/or other materials provided with the
#    distribution.
# 3. Neither the name of the Company nor the names of its contributors
#    may be used to endorse or promote products derived from this
#    software without specific prior written permission.
#
# ALTERNATIVELY, provided that this notice is retained in full, this
# product may be distributed under the terms of the GNU General Public
# License (GPL) version 2 or later, in which case the provisions
# of the GPL apply INSTEAD OF those given above.
#
# This software is provided ``as is'', and any express or implied
# warranties, including, but not limited to, the implied warranties of
# merchantability and fitness for a particular purpose are disclaimed.
# In no event shall the company or contributors be liable for any
# direct, indirect, incidental, special, exemplary, or consequential
# damages (including, but not limited to, procurement of substitute
# goods or services; loss of use, data, or profits; or business
# interruption) however caused and on any theory of liability, whether
# in contract, strict liability, or tort (including negligence or
# otherwise) arising in any way out of the use of this software, even
# if advised of the possibility of such damage.
 
parameters:
    netopeer.data.class: FIT\NetopeerBundle\Models\Data


services:
    data_logger:
        class: Symfony\Bridge\Monolog\Logger
        arguments: [app]
        calls:
             - [pushHandler, [@data_handler]]

    data_handler:
        class: Monolog\Handler\StreamHandler       
        arguments: [%kernel.logs_dir%/%kernel.environment%.data.log]

    DataModel:
        class: %netopeer.data.class%
        arguments: [@service_container, @data_logger]

    XMLoperations:
        class: FIT\NetopeerBundle\Models\XMLoperations
        arguments: [@service_container, @data_logger, @DataModel]

    BaseConnection:
        class: FIT\NetopeerBundle\Entity\BaseConnection
        arguments: [@doctrine.orm.entity_manager, @security.context, @data_logger]

    netopeer.twig.netopeer_twig_extension:
        class: FIT\NetopeerBundle\Twig\NetopeerTwigExtension
        tags:
            - { name: twig.extension }

    winzou_cache:
        factory_service: winzou_cache.factory
        factory_method:  get
        class:           %winzou_cache.driver.abstract%
        arguments:
            - file                       # just modify this value to use another cache
            #- {'cache_dir': /tmp/cache } # you can omit this if you don't use FileCache or if the default value is ok for you

    ajaxController:
        class: FIT\NetopeerBundle\Controller\AjaxController
        arguments:
            container: "@service_container"