parameters:
    netopeer.data.class: FIT\NetopeerBundle\Models\Data


services:
    data_logger:
        class: Symfony\Bridge\Monolog\Logger
        arguments: [app]
        calls:
             - [pushHandler, [@data_handler]]

    data_handler:
        class: Monolog\Handler\StreamHandler       
        arguments: [%kernel.logs_dir%/%kernel.environment%.data.log]

    DataModel:
        class: %netopeer.data.class%
        arguments: [@service_container, @data_logger]

    BaseConnection:
        class: FIT\NetopeerBundle\Entity\BaseConnection
        arguments: [@doctrine.orm.entity_manager, @security.context, @data_logger]

    netopeer.twig.netopeer_twig_extension:
        class: FIT\NetopeerBundle\Twig\NetopeerTwigExtension
        tags:
            - { name: twig.extension }

    winzou_cache:
        factory_service: winzou_cache.factory
        factory_method:  get
        class:           %winzou_cache.driver.abstract%
        arguments:
            - file                       # just modify this value to use another cache
            #- {'cache_dir': /tmp/cache } # you can omit this if you don't use FileCache or if the default value is ok for you